# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloadButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(358, 212)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menuBut = QtWidgets.QPushButton(self.centralwidget)
        self.menuBut.setGeometry(QtCore.QRect(0, 0, 125, 25))
        self.menuBut.setStyleSheet("")
        self.menuBut.setObjectName("menuBut")
        self.downloadBut = QtWidgets.QPushButton(self.centralwidget)
        self.downloadBut.setGeometry(QtCore.QRect(0, 25, 125, 25))
        self.downloadBut.setObjectName("downloadBut")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuBut.setText(_translate("MainWindow", "打开主界面"))
        self.downloadBut.setText(_translate("MainWindow", "从粘贴板下载音乐"))
